
name: MauiReactor

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: ./src/MauiReactor.Build.sln
      Version: 2.0.0-beta

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Update version
      id: update
      uses: vers-one/dotnet-project-version-updater@v1.3
      with:
        files: "./src/MauiReactor/MauiReactor.csproj,./src/MauiReactor.Blazor/MauiReactor.Blazor.csproj,./src/MauiReactor.Canvas/MauiReactor.Canvas.csproj,./src/MauiReactor.Maps/MauiReactor.Maps.csproj,./src/MauiReactor.ScaffoldGenerator/MauiReactor.ScaffoldGenerator.csproj,./src/MauiReactor.TemplatePack/MauiReactor.TemplatePack.csproj,./src/MauiReactor.HotReloadConsole/MauiReactor.HotReloadConsole.csproj"   
        version: $env:Version
        
    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install MAUI workload
      run: dotnet workload install maui
      
    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Build the packages
      run: dotnet build $env:Solution_Name -c Release


  
